name: Build and Deploy Java Application

on:
 push:
  branches:
   - main

jobs:
 build-deploy:
  name: Build and Deploy Java Application
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3

   - name: setup JDK 17
     uses: actions/setup-java@v3
     with:
      distribution: 'corretto'
      java-version: 17

   - name: Unit Tests
     run: mvn test

   - name: Build the Application
     run: mvn clean package
     
