name: Build and Deploy Java Application

on:
 push:
  branches:
   - main

jobs:
 build-deploy:
  name: Build and Deploy Java Application
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3

   - name: setup JDK 17
     uses: actions/setup-java@v3
     with:
      distribution: 'corretto'
      java-version: 17

   - name: Unit Tests
     run: mvn test

   - name: Build the Application
     run: mvn clean package
     
   - name: SonarQube Scan
     uses: SonarSource/sonarqube-scan-action@v1.2.0
     env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
     with:
      host: ${{ secrets.SONAR_HOST_URL }}
      login: ${{ secrets.SONAR_TOKEN }}
      projectBaseDir: spring-boot-app

   - name: Login to DockerHub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

   - name: Build Docker Image
     uses: docker/build-push-action@v4
     with:
      context: .
      file: ./Dockerfile
      push: true
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-app:latest
